version: "3"

services:
    simple-server-a:
        build: ./alpine-apache
        image: nimmis/alpine-apache
        container_name: serverA-10.9.0.5
        volumes:
          - ./alpine-apache/siteA:/web/html 
        tty: true
        ports:
          - "8025:80"
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

    simple-server-b:
        build: ./alpine-apache
        image: nimmis/alpine-apache
        container_name: serverB-10.9.0.6
        volumes:
          - ./alpine-apache/siteB:/web/html
        tty: true
        ports:
          - "8026:80"
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
    simple-parent-site:
        build: ./alpine-apache
        image: nimmis/alpine-apache
        container_name: server-10.9.0.10
        volumes:
          - ./alpine-apache/parentsite:/web/html
        tty: true
        ports:
          - "8010:80"
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.10

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

